import { Component } from '../Component.js';

export class LevelMapView extends Component {
    render() {
        return `
            <div id="view-level-map" class="view hidden" style="padding:0; overflow:hidden;">
                <div class="map-fixed-header" style="position:absolute; top:1rem; left:1rem; z-index:50; pointer-events:none;">
                    <button class="btn-icon back-btn-top" onclick="app.openModeSelection()" title="Geri"
                        style="pointer-events:auto; background:rgba(15, 23, 42, 0.6); backdrop-filter:blur(5px); border:1px solid rgba(255,255,255,0.2);">
                        &larr;
                    </button>
                </div>

                <div class="map-scroll-area" style="overflow-y:auto; height:100%; padding-top:20px;">
                    <div id="level-map-container" class="level-map-container">
                        <!-- Nodes Generated by JS -->
                    </div>
                </div>
            </div>
        `;
    }
}
