import { Component } from '../Component.js';

export class VocabularyGameView extends Component {
    render() {
        return `
            <div id="view-game" class="view hidden">
                <div class="game-header-bar" style="position:relative; justify-content:center;">
                    <div id="level-indicator-container"
                        style="position:absolute; left:1rem; top:50%; transform:translateY(-50%); font-size:1.4rem; color:var(--text-secondary); font-weight:bold;">
                        Seviye <span id="current-level-display" style="color:var(--neon-gold)">1</span>
                    </div>

                    <div id="level-info-container" class="level-info-container hidden"
                        style="flex:0 0 auto; text-align:center;">
                        <span id="level-progress-text"
                            style="font-size:1.8rem; font-weight:800; color:white; text-shadow:0 0 10px rgba(255,255,255,0.3); display:block;">0 / 50</span>
                        <div class="level-progress-track" style="width:150px; margin:5px auto;">
                            <div id="level-progress-fill" class="level-progress-fill" style="width:0%"></div>
                        </div>
                    </div>

                    <div class="live-score" style="display:none;">Skor: <span id="current-score">0</span></div>
                    <div id="game-timer" class="game-timer hidden">02:00</div>
                </div>

                <div class="game-card" style="position:relative;">
                    <div class="card-header" style="justify-content: space-between; align-items: flex-start;">
                        <span id="word-level" class="level-indicator">A1</span>
                        <div id="game-lives" class="game-lives hidden" style="font-size:1.5rem;">❤️❤️❤️</div>
                        <div style="display:flex; flex-direction:column; gap:0.5rem; align-items:center;">
                            <button id="game-star-btn" class="btn-star" onclick="app.toggleGameFavorite()">
                                <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                                    <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2"></polygon>
                                </svg>
                            </button>
                            <button id="btn-speak" class="btn-star" onclick="app.speakCurrentWord()" title="Dinle"
                                style="font-size:1.2rem; display:flex; justify-content:center; align-items:center;">
                                🔊
                            </button>
                        </div>
                    </div>

                    <div class="word-display">
                        <h2 id="target-word">Placeholder</h2>
                    </div>

                    <div id="options-container" class="options-grid">
                        <!-- Options Generated by JS -->
                    </div>
                </div>

                <div style="margin-top:1rem; display:flex; justify-content:between; align-items:center">
                    <button class="btn btn-text" onclick="app.quitGame()">&larr; Vazgeç</button>
                </div>
            </div>
        `;
    }
}
