window.BATCH_4 = [
    { word: 'saddle-bags', meaning: 'heybe', level: 'B2' },
    { word: 'sagacity', meaning: 'keskin zeka, feraset', level: 'C2' },
    { word: 'said', meaning: 'dedi', level: 'A1' },
    { word: 'sat', meaning: 'oturdu', level: 'A1' },
    { word: 'saved', meaning: 'kurtardı, kaydetti', level: 'A2' },
    { word: 'scantlings', meaning: 'keresteler, kirişler', level: 'C2' },
    { word: 'scarcely', meaning: 'neredeyse hiç, güçbela', level: 'C1' },
    { word: 'scarlet', meaning: 'kızıl', level: 'C1' },
    { word: 'schoolroom', meaning: 'derslik', level: 'A2' },
    { word: 'scold', meaning: 'azarlamak', level: 'B2' },
    { word: 'screamed', meaning: 'çığlık attı', level: 'B1' },
    { word: 'scrotumtightening', meaning: 'torba sıkıştıran (mecazi/deniz)', level: 'C2' },
    { word: 'searching', meaning: 'arama, araştıran', level: 'B1' },
    { word: 'seeing', meaning: 'görme', level: 'A1' },
    { word: 'seemed', meaning: 'gibi göründü', level: 'B1' },
    { word: 'seen', meaning: 'görülmüş', level: 'A2' },
    { word: 'sees', meaning: 'görür', level: 'A1' },
    { word: 'seized', meaning: 'ele geçirdi, yakaladı', level: 'B2' },
    { word: 'sensation', meaning: 'his, duygu', level: 'B2' },
    { word: 'senses', meaning: 'duyular', level: 'B1' },
    { word: 'shadowed', meaning: 'gölgeli, izlenen', level: 'B2' },
    { word: 'shadows', meaning: 'gölgeler', level: 'B1' },
    { word: 'shaking', meaning: 'titreme, sallama', level: 'B1' },
    { word: 'sharpened', meaning: 'keskinleşmiş', level: 'B2' },
    { word: 'shave', meaning: 'tıraş olmak', level: 'A2' },
    { word: 'shaven', meaning: 'tıraşlı', level: 'B1' },
    { word: "she'd", meaning: 'o yapardı/yapmıştı (she would/had)', level: 'B1' },
    { word: 'shone', meaning: 'parladı', level: 'B1' },
    { word: 'shook', meaning: 'salladı, titredi', level: 'B1' },
    { word: 'shops', meaning: 'dükkanlar', level: 'A1' },
    { word: 'showed', meaning: 'gösterdi', level: 'A1' },
    { word: 'showing', meaning: 'gösterme', level: 'A1' },
    { word: 'shriek', meaning: 'çığlık', level: 'B2' },
    { word: 'shrieked', meaning: 'feryat etti', level: 'B2' },
    { word: 'shrill', meaning: 'acı, tiz (ses)', level: 'C1' },
    { word: 'shucks', meaning: 'hadi canım (ünlem)', level: 'C2' },
    { word: 'sidewalk', meaning: 'kaldırım', level: 'A2' },
    { word: 'sideways', meaning: 'yanlamasına', level: 'B2' },
    { word: 'sin', meaning: 'günah', level: 'B1' },
    { word: 'sinister', meaning: 'uğursuz, kötü', level: 'C1' },
    { word: 'sins', meaning: 'günahlar', level: 'B1' },
    { word: 'sisters', meaning: 'kız kardeşler', level: 'A1' },
    { word: 'skipped', meaning: 'atladı, sekti', level: 'B1' },
    { word: 'skipping', meaning: 'sekme, atlama', level: 'A2' },
    { word: 'sleeping', meaning: 'uyuyor', level: 'A1' },
    { word: 'sleeps', meaning: 'uyur', level: 'A1' },
    { word: 'sleepy', meaning: 'uykulu', level: 'A1' },
    { word: 'slept', meaning: 'uyudu', level: 'A2' },
    { word: 'slices', meaning: 'dilimler', level: 'B1' },
    { word: 'slipped', meaning: 'kaydı', level: 'B1' },
    { word: 'slowed', meaning: 'yavaşladı', level: 'A2' },
    { word: 'smartly', meaning: 'şık bir şekilde, akıllıca', level: 'B2' },
    { word: 'smiled', meaning: 'gülümsedi', level: 'A2' },
    { word: 'smiles', meaning: 'gülümser', level: 'A1' },
    { word: 'smiling', meaning: 'gülümseyen', level: 'A1' },
    { word: 'snotgreen', meaning: 'sümük yeşili', level: 'C2' },
    { word: 'sofa', meaning: 'kanepe', level: 'A2' },
    { word: 'sold', meaning: 'sattı', level: 'A2' },
    { word: 'solemnly', meaning: 'ciddiyetle', level: 'B2' },
    { word: 'sounded', meaning: 'ses çıkardı, gibi geldi', level: 'B1' },
    { word: 'sounds', meaning: 'sesler', level: 'A1' },
    { word: 'speaking', meaning: 'konuşma', level: 'A1' },
    { word: 'spoken', meaning: 'konuşulan', level: 'B1' },
    { word: 'sprang', meaning: 'fırladı, sıçradı', level: 'C1' },
    { word: 'stain', meaning: 'leke', level: 'B1' },
    { word: 'staircase', meaning: 'merdiven boşluğu', level: 'B2' },
    { word: 'stairhead', meaning: 'merdiven başı', level: 'C2' },
    { word: 'stairs', meaning: 'merdivenler', level: 'A2' },
    { word: 'stared', meaning: 'dik dik baktı', level: 'B1' },
    { word: 'started', meaning: 'başladı', level: 'A1' },
    { word: 'stately', meaning: 'görkemli, asil', level: 'C1' },
    { word: 'stayed', meaning: 'kaldı', level: 'A2' },
    { word: 'steamboat', meaning: 'buharlı gemi', level: 'B1' },
    { word: 'stepped', meaning: 'adım attı', level: 'B1' },
    { word: 'steps', meaning: 'adımlar, basamaklar', level: 'A2' },
    { word: 'sternly', meaning: 'sertçe', level: 'C1' },
    { word: 'stifled', meaning: 'bastırılmış, boğulmuş', level: 'C1' },
    { word: 'stirred', meaning: 'kıpırdadı, karıştırdı', level: 'B2' },
    { word: 'stocks', meaning: 'stoklar, boyunluk (eski)', level: 'C1' },
    { word: 'stood', meaning: 'ayakta durdu', level: 'A2' },
    { word: 'stopped', meaning: 'durdu', level: 'A1' },
    { word: 'stream-of-consciousness', meaning: 'bilinç akışı', level: 'C2' },
    { word: 'stretched', meaning: 'gerindi, uzandı', level: 'B1' },
    { word: 'stump', meaning: 'kütük, çıkmaz', level: 'C1' },
    { word: 'sufficient', meaning: 'yeterli', level: 'B2' },
    { word: 'suggested', meaning: 'önerdi', level: 'B1' },
    { word: 'suits', meaning: 'takım elbiseler, uyar', level: 'B1' },
    { word: 'sullen', meaning: 'suratsız, asık suratlı', level: 'C1' },
    { word: 'sunlight', meaning: 'güneş ışığı', level: 'A2' },
    { word: 'sunny', meaning: 'güneşli', level: 'A1' },
    { word: 'suspected', meaning: 'şüphelendi', level: 'B2' },
    { word: 'sustained', meaning: 'sürdürülen, desteklenen', level: 'C1' },
    { word: 'sweated', meaning: 'terledi', level: 'B1' },
    { word: 'sweet', meaning: 'tatlı', level: 'A1' },
    { word: 'swept', meaning: 'süpürdü', level: 'B1' },
    { word: 'swiftness', meaning: 'sürat, çabukluk', level: 'C1' },
    { word: 'swim', meaning: 'yüzmek', level: 'A1' },
    { word: 'swimming', meaning: 'yüzme', level: 'A1' },
    { word: 'swung', meaning: 'salladı', level: 'B2' },
    { word: 'take', meaning: 'almak', level: 'A1' },
    { word: 'takes', meaning: 'alır', level: 'A1' },
    { word: 'talk', meaning: 'konuşmak', level: 'A1' },
    { word: 'talked', meaning: 'konuştu', level: 'A1' },
    { word: 'talks', meaning: 'konuşur', level: 'A1' },
    { word: 'tea', meaning: 'çay', level: 'A1' },
    { word: 'teach', meaning: 'öğretmek', level: 'A1' },
    { word: 'tear', meaning: 'gözyaşı, yırtmak', level: 'B1' },
    { word: 'technique', meaning: 'teknik', level: 'B1' },
    { word: 'teeth', meaning: 'dişler', level: 'A2' },
    { word: 'tell', meaning: 'anlatmak, söylemek', level: 'A1' },
    { word: 'ten', meaning: 'on', level: 'A1' },
    { word: 'terrible', meaning: 'korkunç', level: 'A2' },
    { word: 'terror', meaning: 'dehşet', level: 'B1' },
    { word: 'terrors', meaning: 'dehşetler', level: 'B1' },
    { word: 'thalatta', meaning: 'deniz (Yunanca)', level: 'C2' },
    { word: 'than', meaning: '...-den (karşılaştırma)', level: 'A1' },
    { word: 'thank', meaning: 'teşekkür etmek', level: 'A1' },
    { word: 'thanks', meaning: 'teşekkürler', level: 'A1' },
    { word: "that's", meaning: 'bu ...', level: 'A1' },
    { word: 'theirs', meaning: 'onlarınki', level: 'B1' },
    { word: 'themselves', meaning: 'kendileri', level: 'B1' },
    { word: 'there', meaning: 'orada, var', level: 'A1' },
    { word: 'thick', meaning: 'kalın', level: 'A2' },
    { word: 'thin', meaning: 'ince', level: 'A2' },
    { word: 'thing', meaning: 'şey', level: 'A1' },
    { word: 'things', meaning: 'şeyler', level: 'A1' },
    { word: 'think', meaning: 'düşünmek', level: 'A1' },
    { word: 'thinks', meaning: 'düşünür', level: 'A1' },
    { word: 'thirty', meaning: 'otuz', level: 'A1' },
    { word: 'thorn', meaning: 'diken', level: 'B2' },
    { word: 'thoughts', meaning: 'düşünceler', level: 'B1' },
    { word: 'three', meaning: 'üç', level: 'A1' },
    { word: 'threw', meaning: 'fırlattı', level: 'B1' },
    { word: 'thrice', meaning: 'üç kez', level: 'C1' },
    { word: 'through', meaning: 'içinden, vasıtasıyla', level: 'A2' },
    { word: 'thrust', meaning: 'itti, soktu', level: 'C1' },
    { word: 'thus', meaning: 'böylece', level: 'B2' },
    { word: 'time', meaning: 'zaman', level: 'A1' },
    { word: 'tin', meaning: 'teneke', level: 'B1' },
    { word: 'tired', meaning: 'yorgun', level: 'A1' },
    { word: 'together', meaning: 'birlikte', level: 'A1' },
    { word: 'told', meaning: 'anlattı, söyledi', level: 'A2' },
    { word: 'tolerable', meaning: 'katlanılabilir', level: 'B2' },
    { word: 'tomorrow', meaning: 'yarın', level: 'A1' },
    { word: 'tone', meaning: 'ton', level: 'B1' },
    { word: 'too', meaning: 'çok, de/da', level: 'A1' },
    { word: 'took', meaning: 'aldı', level: 'A1' },
    { word: 'top', meaning: 'üst, tepe', level: 'A1' },
    { word: 'tossing', meaning: 'fırlatma, savurma', level: 'B2' },
    { word: 'towards', meaning: 'doğru, yönünde', level: 'A2' },
    { word: 'tower', meaning: 'kule', level: 'A2' },
    { word: 'traded', meaning: 'takas etti', level: 'B2' },
    { word: 'tragic', meaning: 'trajik', level: 'B2' },
    { word: 'transformation', meaning: 'dönüşüm', level: 'B2' },
    { word: 'trap', meaning: 'tuzak', level: 'B1' },
    { word: 'treasure', meaning: 'hazine', level: 'B1' },
    { word: 'treasures', meaning: 'hazineler', level: 'B1' },
    { word: 'trees', meaning: 'ağaçlar', level: 'A1' },
    { word: 'tremulous', meaning: 'titrek, ürkek', level: 'C2' },
    { word: 'trick', meaning: 'numara, hile', level: 'B1' },
    { word: 'trifles', meaning: 'ıvır zıvır', level: 'C2' },
    { word: 'tripping', meaning: 'tökezleme, seke seke yürüme', level: 'B2' },
    { word: 'triumph', meaning: 'zafer', level: 'C1' },
    { word: 'trouble', meaning: 'sorun, dert', level: 'A2' },
    { word: 'true', meaning: 'doğru', level: 'A1' },
    { word: 'truly', meaning: 'gerçekten', level: 'B1' },
    { word: 'trust', meaning: 'güvenmek', level: 'A2' },
    { word: 'truth', meaning: 'gerçek', level: 'B1' },
    { word: 'try', meaning: 'denemek', level: 'A1' },
    { word: 'turn', meaning: 'dönmek, sıra', level: 'A1' },
    { word: 'turned', meaning: 'döndü', level: 'A2' },
    { word: 'tussore-silk', meaning: 'yabani ipek', level: 'C2' },
    { word: 'twelve', meaning: 'on iki', level: 'A1' },
    { word: 'twenty', meaning: 'yirmi', level: 'A1' },
    { word: 'twenty-one', meaning: 'yirmi bir', level: 'A1' },
    { word: 'twisted', meaning: 'bükülmüş, çarpık', level: 'B2' },
    { word: 'two', meaning: 'iki', level: 'A1' },
    { word: 'understood', meaning: 'anladı', level: 'A2' },
    { word: 'undisturbed', meaning: 'rahatsız edilmemiş', level: 'C1' },
    { word: 'ungirdled', meaning: 'kushaksız, kemersiz', level: 'C2' },
    { word: 'unlock', meaning: 'kilit açmak', level: 'B1' },
    { word: 'unprecedented', meaning: 'eşi benzeri görülmemiş', level: 'C2' },
    { word: 'untonsured', meaning: 'rahip tıraşı olmamış', level: 'C2' },
    { word: 'untouched', meaning: 'dokunulmamış', level: 'B2' },
    { word: 'uses', meaning: 'kullanır', level: 'A1' },
    { word: 'vain', meaning: 'kibirli, beyhude', level: 'B2' },
    { word: 'vex', meaning: 'kızdırmak, üzmek', level: 'C2' },
    { word: 'vice', meaning: 'ahlaksızlık, kusur', level: 'C2' },
    { word: 'victims', meaning: 'kurbanlar', level: 'B2' },
    { word: 'vigorously', meaning: 'güçlü bir şekilde', level: 'C1' },
    { word: 'villains', meaning: 'kötü adamlar, hainler', level: 'B2' },
    { word: 'visitors', meaning: 'ziyaretçiler', level: 'A2' },
    { word: 'waited', meaning: 'bekledi', level: 'A1' },
    { word: 'wakes', meaning: 'uyanır', level: 'A2' },
    { word: 'walked', meaning: 'yürüdü', level: 'A1' },
    { word: 'walks', meaning: 'yürür', level: 'A1' },
    { word: 'wanted', meaning: 'istedi', level: 'A1' },
    { word: 'wary', meaning: 'temkinli', level: 'C1' },
    { word: "wasn't", meaning: 'değildi', level: 'A1' },
    { word: 'watched', meaning: 'izledi', level: 'A1' },
    { word: 'watcher', meaning: 'gözcü, izleyici', level: 'B2' },
    { word: 'watching', meaning: 'izliyor', level: 'A1' },
    { word: 'wearily', meaning: 'yorgunlukla', level: 'B2' },
    { word: 'weeks', meaning: 'haftalar', level: 'A1' },
    { word: 'weird', meaning: 'tuhaf', level: 'B1' },
    { word: 'welled', meaning: 'fışkırdı, doldu', level: 'C2' },
    { word: 'went', meaning: 'gitti', level: 'A1' },
    { word: 'wheedling', meaning: 'tatlı dille kandırma', level: 'C2' },
    { word: 'whistle', meaning: 'ıslık, düdük', level: 'B1' },
    { word: 'whistles', meaning: 'ıslıklar', level: 'B1' },
    { word: 'whitewash', meaning: 'badana', level: 'C1' },
    { word: 'whitewashed', meaning: 'badanalı', level: 'C1' },
    { word: 'whitewashing', meaning: 'badana yapma', level: 'C1' },
    { word: "who's", meaning: 'kim (who is)', level: 'A1' },
    { word: 'whorls', meaning: 'helezonlar, kıvrımlar', level: 'C2' },
    { word: 'winding', meaning: 'kıvrımlı, dolambaçlı', level: 'B2' },
    { word: 'wisely', meaning: 'bilgece', level: 'B2' },
    { word: 'wisest', meaning: 'en bilge', level: 'B2' },
    { word: 'wished', meaning: 'diledi', level: 'A2' },
    { word: "woman's", meaning: 'kadının', level: 'A1' },
    { word: 'women', meaning: 'kadınlar', level: 'A1' },
    { word: "won't", meaning: 'yapmayacak', level: 'A1' },
    { word: 'wordplay', meaning: 'kelime oyunu', level: 'C1' },
    { word: 'wore', meaning: 'giydi', level: 'A2' },
    { word: 'worked', meaning: 'çalıştı', level: 'A1' },
    { word: 'works', meaning: 'çalışır, eserler', level: 'A1' },
    { word: "world's", meaning: 'dünyanın', level: 'A1' },
    { word: "wouldn't", meaning: 'yapmazdı', level: 'B1' },
    { word: 'wreaths', meaning: 'çelenkler, halkalar', level: 'C2' },
    { word: 'wronged', meaning: 'haksızlığa uğramış', level: 'C1' },
    { word: 'yards', meaning: 'yardalar', level: 'B1' },
    { word: 'years', meaning: 'yıllar', level: 'A1' },
    { word: 'yell', meaning: 'bağırmak', level: 'B1' },
    { word: "you'd", meaning: 'sen yapardın', level: 'B1' },
    { word: "you'll", meaning: 'sen yapacaksın', level: 'A1' },
    { word: "you're", meaning: "sen ...'sın", level: 'A1' },
    { word: 'younger', meaning: 'daha genç', level: 'A1' }
];
