window.BATCH_1 = [
    { word: 'accumulated', meaning: 'birikmiş, toplanmış', level: 'B2' },
    { word: 'ached', meaning: 'ağrıdı, sızladı', level: 'B1' },
    { word: 'added', meaning: 'ekledi', level: 'A1' },
    { word: 'adonis', meaning: 'Adonis (çok yakışıklı erkek)', level: 'C1' },
    { word: 'adored', meaning: 'çok sevdi, tapındı', level: 'B2' },
    { word: 'ages', meaning: 'çağlar, uzun yıllar', level: 'B1' },
    { word: "ain't", meaning: 'değil (argo)', level: 'B2' },
    { word: 'allusions', meaning: 'anıştırmalar, imalar', level: 'C2' },
    { word: 'amazement', meaning: 'şaşkınlık, hayret', level: 'B2' },
    { word: 'amidst', meaning: 'ortasında, arasında', level: 'B2' },
    { word: 'animals', meaning: 'hayvanlar', level: 'A1' },
    { word: 'answered', meaning: 'cevapladı', level: 'A2' },
    { word: 'appeared', meaning: 'göründü', level: 'A2' },
    { word: 'appears', meaning: 'görünür', level: 'A2' },
    { word: 'argued', meaning: 'tartıştı', level: 'B1' },
    { word: 'arises', meaning: 'ortaya çıkar', level: 'B2' },
    { word: 'arose', meaning: 'ortaya çıktı', level: 'B2' },
    { word: 'arrives', meaning: 'varır, ulaşır', level: 'A2' },
    { word: 'artists', meaning: 'sanatçılar', level: 'A2' },
    { word: 'asked', meaning: 'sordu', level: 'A1' },
    { word: 'ate', meaning: 'yedi', level: 'A2' },
    { word: 'audacity', meaning: 'küstahlık, cüret', level: 'C1' },
    { word: 'awaking', meaning: 'uyanma', level: 'B1' },
    { word: 'awhile', meaning: 'bir süre', level: 'Old' },
    { word: 'bade', meaning: 'buyurdu, veda etti', level: 'Old' },
    { word: 'barracks', meaning: 'kışla', level: 'B2' },
    { word: 'bearing', meaning: 'taşıyan, duruş', level: 'B2' },
    { word: 'beating', meaning: 'dövme, kalp atışı', level: 'B1' },
    { word: 'became', meaning: 'oldu', level: 'A2' },
    { word: 'becoming', meaning: 'oluyor, yakışan', level: 'B1' },
    { word: 'began', meaning: 'başladı', level: 'A2' },
    { word: 'begging', meaning: 'yalvarma, dilenme', level: 'B1' },
    { word: 'begins', meaning: 'başlar', level: 'A1' },
    { word: 'believed', meaning: 'inandı', level: 'A2' },
    { word: 'belonged', meaning: 'aitti', level: 'B1' },
    { word: 'betrayal', meaning: 'ihanet', level: 'C1' },
    { word: 'birds', meaning: 'kuşlar', level: 'A1' },
    { word: 'blandly', meaning: 'yumuşakça, sakince', level: 'C1' },
    { word: 'blessed', meaning: 'kutsadı', level: 'B1' },
    { word: 'blinking', meaning: 'göz kırpma', level: 'B1' },
    { word: 'blood-spot', meaning: 'kan lekesi', level: 'B1' },
    { word: 'bloody', meaning: 'kanlı, lanet (argo)', level: 'B1' },
    { word: 'blossoms', meaning: 'çiçekler (ağaç)', level: 'B1' },
    { word: 'boards', meaning: 'tahtalar, panolar', level: 'B1' },
    { word: 'bosom', meaning: 'bağır, göğüs', level: 'C1' },
    { word: 'bought', meaning: 'satın aldı', level: 'A2' },
    { word: 'boys', meaning: 'erkek çocuklar', level: 'A1' },
    { word: 'branches', meaning: 'dallar', level: 'B1' },
    { word: 'bribe', meaning: 'rüşvet', level: 'B2' },
    { word: 'bringing', meaning: 'getirme', level: 'A2' },
    { word: 'briskly', meaning: 'canlı bir şekilde, çabucak', level: 'B2' },
    { word: 'broke', meaning: 'kırdı, bozuldu', level: 'A2' },
    { word: 'bronze', meaning: 'bronz', level: 'B1' },
    { word: 'brought', meaning: 'getirdi', level: 'A2' },
    { word: 'brows', meaning: 'kaşlar, alın', level: 'B1' },
    { word: 'bucket', meaning: 'kova', level: 'B1' },
    { word: 'burden', meaning: 'yük, sorumluluk', level: 'B2' },
    { word: 'bursting', meaning: 'patlayan, dopdolu', level: 'B2' },
    { word: 'called', meaning: 'aradı, isimlendirdi', level: 'A1' },
    { word: 'calls', meaning: 'arar, çağırır', level: 'A1' },
    { word: 'calmly', meaning: 'sakin bir şekilde', level: 'B1' },
    { word: 'came', meaning: 'geldi', level: 'A1' },
    { word: 'cannot', meaning: 'yapamaz', level: 'A1' },
    { word: 'captured', meaning: 'yakaladı, ele geçirdi', level: 'B2' },
    { word: 'carelessly', meaning: 'dikkatsizce', level: 'B1' },
    { word: 'catches', meaning: 'yakalar', level: 'A2' },
    { word: 'catching', meaning: 'yakalama', level: 'A2' },
    { word: 'cautious', meaning: 'dikkatli, tedbirli', level: 'B2' },
    { word: 'ceased', meaning: 'sona erdi, durdu', level: 'C1' },
    { word: 'ceasing', meaning: 'durma, kesilme', level: 'C1' },
    { word: 'cents', meaning: 'sentler (para birimi)', level: 'A1' },
    { word: 'chairs', meaning: 'sandalyeler', level: 'A1' },
    { word: 'changed', meaning: 'değişti', level: 'A1' },
    { word: 'chap', meaning: 'ahbap, adam', level: 'B2' },
    { word: 'chaps', meaning: 'ahbaplar', level: 'B2' },
    { word: 'charming', meaning: 'cazibeli, büyüleyici', level: 'B1' },
    { word: 'chatted', meaning: 'sohbet etti', level: 'A2' },
    { word: 'cheeks', meaning: 'yanaklar', level: 'B1' },
    { word: 'chew', meaning: 'çiğnemek', level: 'B1' },
    { word: 'chews', meaning: 'çiğner', level: 'B1' },
    { word: 'chuckled', meaning: 'kıs kıs güldü', level: 'B2' },
    { word: 'cigarettes', meaning: 'sigaralar', level: 'A2' },
    { word: 'clearing', meaning: 'temizleme, açıklık alan', level: 'B1' },
    { word: 'cleverly', meaning: 'akıllıca', level: 'B1' },
    { word: 'closes', meaning: 'kapanır', level: 'A1' },
    { word: 'coal-black', meaning: 'kömür karası', level: 'B2' },
    { word: 'coarsely', meaning: 'kaba bir şekilde', level: 'C1' },
    { word: 'coats', meaning: 'montlar', level: 'A1' },
    { word: 'coldly', meaning: 'soğukça', level: 'B1' },
    { word: 'combs', meaning: 'taraklar', level: 'B1' },
    { word: 'comes', meaning: 'gelir', level: 'A1' },
    { word: 'complexity', meaning: 'karmaşıklık', level: 'B2' },
    { word: 'comprehended', meaning: 'kavradı, anladı', level: 'C1' },
    { word: 'concealment', meaning: 'gizleme', level: 'C1' },
    { word: 'conceived', meaning: 'tasarladı, kafasına koydu', level: 'C1' },
    { word: 'confession', meaning: 'itiraf', level: 'B2' },
    { word: 'conscience', meaning: 'vicdan', level: 'B2' },
    { word: 'consciousness', meaning: 'bilinç', level: 'B2' },
    { word: 'consent', meaning: 'rıza, onay', level: 'B2' },
    { word: 'considered', meaning: 'düşündü, hesaba kattı', level: 'A2' },
    { word: 'consists', meaning: '-den oluşur', level: 'B1' },
    { word: 'contemplated', meaning: 'düşünüp taşındı', level: 'C1' },
    { word: 'continued', meaning: 'devam etti', level: 'A2' },
    { word: 'contradict', meaning: 'çelişmek, itiraz etmek', level: 'C1' },
    { word: 'convey', meaning: 'iletmek, aktarmak', level: 'B2' },
    { word: 'convinced', meaning: 'ikna olmuş', level: 'B1' },
    { word: 'corpse', meaning: 'ceset', level: 'C1' },
    { word: 'corrupt', meaning: 'yozlaşmış', level: 'B2' },
    { word: 'counted', meaning: 'saydı', level: 'A2' },
    { word: 'covet', meaning: 'imrenmek, göz dikmek', level: 'C2' },
    { word: 'crammed', meaning: 'tıkıştırdı', level: 'B2' },
    { word: 'cried', meaning: 'ağladı, bağırdı', level: 'A2' },
    { word: 'crossed', meaning: 'karşıya geçti, çapraz', level: 'A2' },
    { word: 'crosses', meaning: 'haçlar, geçişler', level: 'B1' },
    { word: 'cruelty', meaning: 'zalimlik', level: 'B2' },
    { word: 'crying', meaning: 'ağlama', level: 'A2' },
    { word: 'cunningly', meaning: 'kurnazca', level: 'C1' },
    { word: 'curled', meaning: 'kıvrıldı', level: 'B1' },
    { word: 'curtains', meaning: 'perdeler', level: 'A2' },
    { word: 'damn', meaning: 'lanet, kahretsin', level: 'B1' },
    { word: 'darkened', meaning: 'karardı', level: 'B1' },
    { word: 'days', meaning: 'günler', level: 'A1' },
    { word: 'dearly', meaning: 'içtenlikle, pahalıya', level: 'B2' },
    { word: 'deed', meaning: 'eylem, tapu', level: 'C1' },
    { word: 'deeds', meaning: 'işler, eylemler', level: 'C1' },
    { word: 'deepening', meaning: 'derinleşen', level: 'C1' },
    { word: 'defines', meaning: 'tanımlar', level: 'B1' },
    { word: 'degrees', meaning: 'dereceler', level: 'B1' },
    { word: 'delicate', meaning: 'hassas, narin', level: 'B2' },
    { word: 'delight', meaning: 'sevinç, zevk', level: 'B1' },
    { word: 'deposited', meaning: 'koydu, yatırdı', level: 'C1' },
    { word: 'derision', meaning: 'alay, küçümseme', level: 'C2' },
    { word: 'described', meaning: 'tanımladı', level: 'A2' },
    { word: 'desire', meaning: 'arzu, istek', level: 'B2' },
    { word: 'desired', meaning: 'arzulanan, istenen', level: 'B2' },
    { word: 'desperate', meaning: 'umutsuz', level: 'B2' },
    { word: 'destroyed', meaning: 'yok etti', level: 'B1' },
    { word: 'destruction', meaning: 'yıkım', level: 'B2' },
    { word: 'detected', meaning: 'tespit etti', level: 'B2' },
    { word: "didn't", meaning: 'yapmadı', level: 'A1' },
    { word: 'dipped', meaning: 'daldırdı', level: 'B1' },
    { word: 'discovered', meaning: 'keşfetti', level: 'B1' },
    { word: 'dismembered', meaning: 'parçalara ayırdı', level: 'C2' },
    { word: 'displeased', meaning: 'memnuniyetsiz', level: 'C1' },
    { word: 'dissemble', meaning: 'gizlemek, ikiyüzlülük yapmak', level: 'C2' },
    { word: 'dissimulation', meaning: 'iki yüzlülük, gizleme', level: 'C2' },
    { word: 'distinct', meaning: 'belirgin', level: 'B2' },
    { word: 'distracted', meaning: 'dikkatini dağıttı', level: 'B1' },
    { word: 'divan', meaning: 'divan, sedir', level: 'C1' },
    { word: "doesn't", meaning: 'yapmaz', level: 'A1' },
    { word: 'dollars', meaning: 'dolar', level: 'A1' },
    { word: "don't", meaning: 'yapma', level: 'A1' },
    { word: 'done', meaning: 'yapılmış, bitmiş', level: 'A1' },
    { word: 'doorway', meaning: 'kapı aralığı', level: 'B1' },
    { word: 'dragged', meaning: 'sürükledi', level: 'B1' },
    { word: 'dreadful', meaning: 'korkunç', level: 'B2' },
    { word: 'dreadfully', meaning: 'korkunç bir şekilde', level: 'B2' },
    { word: 'drew', meaning: 'çizdi, çekti', level: 'A2' },
    { word: 'droned', meaning: 'vızıldadı', level: 'C1' },
    { word: 'drove', meaning: 'sürdü', level: 'A2' }
];
