window.BATCH_2 = [
    { word: 'dulled', meaning: 'körelmiş, donuklaşmış', level: 'C1' },
    { word: 'dying', meaning: 'ölmekte olan', level: 'B1' },
    { word: 'earnestly', meaning: 'ciddiyetle, samimiyetle', level: 'B2' },
    { word: 'ears', meaning: 'kulaklar', level: 'A1' },
    { word: 'eating', meaning: 'yeme', level: 'A1' },
    { word: 'eighth', meaning: 'sekizinci', level: 'A2' },
    { word: 'eighty-seven', meaning: 'seksen yedi', level: 'A1' },
    { word: 'elegant', meaning: 'zarif, şık', level: 'B1' },
    { word: 'elevated', meaning: 'yükseltilmiş, yüce', level: 'C1' },
    { word: 'embodiment', meaning: 'somutlaşmış hali, simge', level: 'C2' },
    { word: 'ends', meaning: 'biter, sonlar', level: 'A1' },
    { word: 'entered', meaning: 'girdi', level: 'A2' },
    { word: 'entering', meaning: 'girme', level: 'A2' },
    { word: 'envied', meaning: 'kıskandı, gıpta etti', level: 'B2' },
    { word: 'equine', meaning: 'ata ait, at gibi', level: 'C2' },
    { word: 'eras', meaning: 'çağlar, dönemler', level: 'B2' },
    { word: 'ere', meaning: 'önce (eski)', level: 'Old' },
    { word: 'establishes', meaning: 'kurar, tesis eder', level: 'B2' },
    { word: 'eternal', meaning: 'ebedi, sonsuz', level: 'B2' },
    { word: 'eternally', meaning: 'ebediyen', level: 'B2' },
    { word: 'examined', meaning: 'inceledi, muayene etti', level: 'B1' },
    { word: 'excerpt', meaning: 'alıntı', level: 'B2' },
    { word: 'exhibit', meaning: 'sergilemek', level: 'B1' },
    { word: 'exploration', meaning: 'keşif', level: 'B1' },
    { word: 'eyebrows', meaning: 'kaşlar', level: 'B1' },
    { word: 'eyes', meaning: 'gözler', level: 'A1' },
    { word: 'faced', meaning: 'yüzleşti, dönük', level: 'B1' },
    { word: 'fancied', meaning: 'hayal etti, sandı', level: 'C1' },
    { word: 'fanciful', meaning: 'süslü, hayali', level: 'C2' },
    { word: 'fastening', meaning: 'tutturma, bağlama', level: 'B2' },
    { word: 'fatigues', meaning: 'yorgunluklar (askeri iş)', level: 'C2' },
    { word: 'fearful', meaning: 'korkunç, korkak', level: 'B1' },
    { word: 'features', meaning: 'özellikler, yüz hatları', level: 'B1' },
    { word: 'feelings', meaning: 'hisler', level: 'A2' },
    { word: 'feet', meaning: 'ayaklar', level: 'A1' },
    { word: 'fell', meaning: 'düştü', level: 'A2' },
    { word: 'felt', meaning: 'hissetti', level: 'A2' },
    { word: 'fetch', meaning: 'gidip getirmek', level: 'B1' },
    { word: 'filled', meaning: 'dolu, doldurulmuş', level: 'A2' },
    { word: 'finely', meaning: 'ince bir şekilde, güzelce', level: 'B2' },
    { word: 'fingers', meaning: 'parmaklar', level: 'A1' },
    { word: 'finical', meaning: 'titiz, süslü', level: 'C2' },
    { word: 'finished', meaning: 'bitti, bitirdi', level: 'A1' },
    { word: 'flame-like', meaning: 'ateş gibi', level: 'B2' },
    { word: 'flitted', meaning: 'uçuştu, süzüldü', level: 'C2' },
    { word: 'flooring', meaning: 'döşeme', level: 'B1' },
    { word: 'fluently', meaning: 'akıcı bir şekilde', level: 'B1' },
    { word: 'flung', meaning: 'fırlattı', level: 'B2' },
    { word: 'folds', meaning: 'kıvrımlar', level: 'B1' },
    { word: 'followed', meaning: 'takip etti', level: 'A2' },
    { word: 'foresight', meaning: 'öngörü', level: 'C1' },
    { word: 'forth', meaning: 'ileri, dışarı', level: 'B2' },
    { word: 'frank', meaning: 'dobra, içten', level: 'B2' },
    { word: 'frankly', meaning: 'açıkçası', level: 'B1' },
    { word: 'friends', meaning: 'arkadaşlar', level: 'A1' },
    { word: 'gaily', meaning: 'neşeyle', level: 'C1' },
    { word: 'games', meaning: 'oyunlar', level: 'A1' },
    { word: 'gathering', meaning: 'toplama, toplanma', level: 'B1' },
    { word: 'gave', meaning: 'verdi', level: 'A1' },
    { word: 'gay', meaning: 'neşeli (eski kullanım)', level: 'Old' },
    { word: 'gazing', meaning: 'dik dik bakma', level: 'B2' },
    { word: 'gentlemen', meaning: 'beyefendiler', level: 'A2' },
    { word: 'gently', meaning: 'nazikçe', level: 'B1' },
    { word: 'genuine', meaning: 'hakiki, gerçek', level: 'B2' },
    { word: 'gesticulations', meaning: 'el kol hareketleri', level: 'C2' },
    { word: 'getting', meaning: 'alma, olma', level: 'A1' },
    { word: 'gifts', meaning: 'hediyeler', level: 'A1' },
    { word: 'girls', meaning: 'kızlar', level: 'A1' },
    { word: 'given', meaning: 'verilmiş', level: 'A2' },
    { word: 'gleam', meaning: 'parıltı', level: 'C1' },
    { word: 'glistening', meaning: 'parıldayan', level: 'C1' },
    { word: 'gloomily', meaning: 'kasvetli bir şekilde', level: 'B2' },
    { word: 'going', meaning: 'gidiyor', level: 'A1' },
    { word: 'gone', meaning: 'gitmiş', level: 'A2' },
    { word: 'got', meaning: 'aldı, sahip oldu', level: 'A1' },
    { word: 'gown', meaning: 'sabahlık, elbise', level: 'B1' },
    { word: 'grained', meaning: 'taneli, desenli', level: 'C1' },
    { word: 'gravely', meaning: 'ciddiyetle', level: 'B2' },
    { word: 'greatest', meaning: 'en büyük', level: 'A2' },
    { word: 'grew', meaning: 'büyüdü, oldu', level: 'B1' },
    { word: 'grief', meaning: 'keder', level: 'B2' },
    { word: 'groan', meaning: 'inilti', level: 'B2' },
    { word: 'grotesque', meaning: 'ucube, acayip', level: 'C1' },
    { word: 'growled', meaning: 'hırladı', level: 'B2' },
    { word: 'grows', meaning: 'büyür', level: 'A1' },
    { word: 'guilt', meaning: 'suçluluk', level: 'B2' },
    { word: 'gunrest', meaning: 'silah dayanağı', level: 'C2' },
    { word: 'gurgling', meaning: 'çağlayan, fokurdayan', level: 'C1' },
    { word: 'haircut', meaning: 'saç kesimi', level: 'A2' },
    { word: 'halfway', meaning: 'yarı yolda', level: 'B1' },
    { word: 'halted', meaning: 'durdu', level: 'B2' },
    { word: 'happened', meaning: 'oldu, meydana geldi', level: 'A2' },
    { word: "hasn't", meaning: 'yapmadı (has not)', level: 'A1' },
    { word: 'hastily', meaning: 'aceleyle', level: 'B2' },
    { word: 'hateful', meaning: 'nefret dolu', level: 'B2' },
    { word: 'haunted', meaning: 'perili, aklından çıkmayan', level: 'B2' },
    { word: 'healthily', meaning: 'sağlıklı bir şekilde', level: 'B1' },
    { word: 'heard', meaning: 'duydu', level: 'A2' },
    { word: 'hears', meaning: 'duyar', level: 'A2' },
    { word: 'heartbeat', meaning: 'kalp atışı', level: 'B1' },
    { word: 'hedonism', meaning: 'hazcılık', level: 'C2' },
    { word: 'held', meaning: 'tuttu', level: 'B1' },
    { word: 'hellenic', meaning: 'Yunan, Helenik', level: 'C2' },
    { word: 'helps', meaning: 'yardım eder', level: 'A1' },
    { word: 'hewed', meaning: 'yonttu, kesti', level: 'C2' },
    { word: 'hewing', meaning: 'yontma', level: 'C2' },
    { word: 'hid', meaning: 'sakladı', level: 'B1' },
    { word: 'hideous', meaning: 'iğrenç, korkunç', level: 'B2' },
    { word: 'hoarsened', meaning: 'kısılmış (ses)', level: 'C2' },
    { word: 'honey-coloured', meaning: 'bal rengi', level: 'B2' },
    { word: 'honey-sweet', meaning: 'bal gibi tatlı', level: 'B2' },
    { word: 'hoof', meaning: 'toynak', level: 'B2' },
    { word: 'hopeless', meaning: 'umutsuz', level: 'B1' },
    { word: 'horn', meaning: 'boynuz, korna', level: 'B1' },
    { word: 'horses', meaning: 'atlar', level: 'A1' },
    { word: 'hued', meaning: 'renkli, tonlu', level: 'C2' },
    { word: 'hunters', meaning: 'avcılar', level: 'B1' },
    { word: 'hyperborean', meaning: 'kuzeyli, çok soğuk', level: 'C2' },
    { word: 'hypocritical', meaning: 'ikiyüzlü', level: 'B2' },
    { word: "i'll", meaning: 'yapacağım', level: 'A1' },
    { word: "i'm", meaning: "ben ...'ım", level: 'A1' },
    { word: 'idle', meaning: 'aylak, boş', level: 'B1' },
    { word: 'ignorance', meaning: 'cehalet', level: 'B2' },
    { word: 'imagines', meaning: 'hayal eder', level: 'B1' },
    { word: 'immobile', meaning: 'hareketsiz', level: 'C1' },
    { word: 'impaled', meaning: 'saplanmış', level: 'C1' },
    { word: 'increased', meaning: 'arttı', level: 'B1' },
    { word: 'indigestion', meaning: 'hazımsızlık', level: 'B2' },
    { word: 'innumerable', meaning: 'sayısız, hadsiz hesapsız', level: 'C1' },
    { word: 'instant', meaning: 'an', level: 'B1' },
    { word: 'intoned', meaning: 'ağır ağır söyledi', level: 'C2' },
    { word: 'intricate', meaning: 'karmaşık, girift', level: 'C1' },
    { word: 'introduced', meaning: 'tanıttı', level: 'A2' },
    { word: 'introducing', meaning: 'tanıtma', level: 'A2' },
    { word: "isn't", meaning: 'değil', level: 'A1' },
    { word: "it's", meaning: 'bu ...', level: 'A1' },
    { word: 'items', meaning: 'eşyalar, maddeler', level: 'A2' },
    { word: 'ivory', meaning: 'fildişi', level: 'C1' },
    { word: 'jade-faced', meaning: 'yeşim yüzlü (soluk)', level: 'C2' },
    { word: 'jejune', meaning: 'yavan, basit', level: 'C2' },
    { word: 'jest', meaning: 'şaka, alay', level: 'C1' },
    { word: 'jesuit', meaning: 'Cizvit', level: 'C2' },
    { word: 'jowl', meaning: 'gıdı, çene altı', level: 'C2' },
    { word: 'jug', meaning: 'sürahi', level: 'B1' },
    { word: 'kept', meaning: 'tuttu, sakladı', level: 'A2' },
    { word: 'killed', meaning: 'öldürdü', level: 'A2' },
    { word: 'kinder', meaning: 'daha nazik', level: 'B1' },
    { word: 'kinds', meaning: 'türler', level: 'A2' },
    { word: 'kinswoman', meaning: 'kadın akraba', level: 'C2' },
    { word: 'kite', meaning: 'uçurtma', level: 'A2' },
    { word: 'kneel', meaning: 'diz çökmek', level: 'B1' },
    { word: 'knees', meaning: 'dizler', level: 'B1' },
    { word: 'knelt', meaning: 'diz çöktü', level: 'B1' },
    { word: 'knew', meaning: 'biliyordu', level: 'A1' },
    { word: 'knocking', meaning: 'vurma, tıkırtı', level: 'B1' },
    { word: 'labors', meaning: 'emekler, işler', level: 'C1' },
    { word: 'laburnum', meaning: 'sarı salkım ağacı', level: 'C2' },
    { word: 'laid', meaning: 'koydu, yatırdı', level: 'B1' },
    { word: 'lantern', meaning: 'fener', level: 'B1' },
    { word: 'latch', meaning: 'kapı mandalı', level: 'B2' },
    { word: 'lather', meaning: 'köpük (sabun)', level: 'C1' },
    { word: 'lathered', meaning: 'köpürttü', level: 'C1' },
    { word: 'laughed', meaning: 'güldü', level: 'A1' },
    { word: 'laughing', meaning: 'gülme', level: 'A1' },
    { word: 'laughs', meaning: 'güler', level: 'A1' },
    { word: 'leads', meaning: 'yol açar, yönetir', level: 'B1' },
    { word: 'leaned', meaning: 'yaslandı, eğildi', level: 'B2' },
    { word: 'leaning', meaning: 'yaslanma, eğilme', level: 'B2' },
    { word: 'leaped', meaning: 'sıçradı', level: 'B2' },
    { word: 'learned', meaning: 'öğrendi', level: 'A1' },
    { word: 'led', meaning: 'yol gösterdi', level: 'B1' },
    { word: 'legs', meaning: 'bacaklar', level: 'A1' },
    { word: 'lemme', meaning: 'bırak (let me)', level: 'A2' },
    { word: 'lets', meaning: 'izin verir', level: 'B1' },
    { word: 'lifting', meaning: 'kaldırma', level: 'B1' },
    { word: 'lilac', meaning: 'leylak', level: 'C1' },
    { word: 'lines', meaning: 'satırlar, çizgiler', level: 'A1' },
    { word: 'linguistic', meaning: 'dilbilimsel', level: 'C1' },
    { word: 'lips', meaning: 'dudaklar', level: 'B1' },
    { word: 'lived', meaning: 'yaşadı', level: 'A1' },
    { word: 'loaf', meaning: 'somun (ekmek)', level: 'C1' },
    { word: 'locked', meaning: 'kilitli', level: 'A2' },
    { word: 'longer', meaning: 'daha uzun', level: 'A2' },
    { word: 'looked', meaning: 'baktı, göründü', level: 'A1' },
    { word: 'looks', meaning: 'bakar, görünür', level: 'A1' },
    { word: 'louder', meaning: 'daha yüksek sesli', level: 'A2' },
    { word: 'loved', meaning: 'sevdi', level: 'A1' },
    { word: 'lunged', meaning: 'ileri atıldı', level: 'C1' },
    { word: 'lying', meaning: 'uzanma, yalan söyleme', level: 'B1' }
];
