window.BATCH_3 = [
    { word: "ma'am", meaning: 'hanımefendi', level: 'A2' },
    { word: 'made', meaning: 'yaptı', level: 'A1' },
    { word: 'madmen', meaning: 'deliler', level: 'C1' },
    { word: 'madness', meaning: 'delilik', level: 'B2' },
    { word: 'magi', meaning: 'müneccimler (bilge adamlar)', level: 'C2' },
    { word: 'mailboat', meaning: 'posta gemisi', level: 'C2' },
    { word: 'makes', meaning: 'yapar', level: 'A1' },
    { word: 'making', meaning: 'yapma', level: 'A1' },
    { word: "man's", meaning: 'adamın', level: 'A1' },
    { word: 'marbles', meaning: 'bilyeler', level: 'B1' },
    { word: 'men', meaning: 'adamlar', level: 'A1' },
    { word: 'mentioned', meaning: 'bahsetti', level: 'B1' },
    { word: 'messmates', meaning: 'yemek arkadaşları (askeri/denizci)', level: 'C2' },
    { word: 'missus', meaning: 'hanımefendi (halk ağzı)', level: 'B2' },
    { word: 'mockery', meaning: 'alay', level: 'C1' },
    { word: 'momentary', meaning: 'anlık', level: 'B2' },
    { word: 'monologue', meaning: 'monolog', level: 'B2' },
    { word: 'monstrous', meaning: 'canavarca, kocaman', level: 'B2' },
    { word: 'mountains', meaning: 'dağlar', level: 'A1' },
    { word: 'mounted', meaning: 'bindi, tırmandı', level: 'B2' },
    { word: 'moved', meaning: 'hareket etti, taşındı', level: 'A2' },
    { word: 'muffled', meaning: 'boğuk (ses)', level: 'C1' },
    { word: 'mulatto', meaning: 'melez', level: 'C2' },
    { word: 'munched', meaning: 'kıtır kıtır yedi', level: 'C1' },
    { word: 'murmured', meaning: 'mırıldandı', level: 'B2' },
    { word: "narrator's", meaning: 'anlatıcının', level: 'B2' },
    { word: 'needed', meaning: 'ihtiyacı vardı', level: 'A1' },
    { word: 'nerves', meaning: 'sinirler', level: 'B1' },
    { word: 'nicely', meaning: 'güzelce', level: 'A2' },
    { word: 'nights', meaning: 'geceler', level: 'A1' },
    { word: 'notes', meaning: 'notlar', level: 'A1' },
    { word: 'noticed', meaning: 'fark etti', level: 'B1' },
    { word: 'noticing', meaning: 'fark etme', level: 'B1' },
    { word: 'obliged', meaning: 'mecbur, minnettar', level: 'C1' },
    { word: 'odour', meaning: 'koku', level: 'B2' },
    { word: 'officers', meaning: 'memurlar, subaylar', level: 'B1' },
    { word: 'older', meaning: 'daha yaşlı', level: 'A1' },
    { word: 'omnipotence', meaning: 'kadir-i mutlaklık (her şeye gücü yetme)', level: 'C2' },
    { word: "one's", meaning: 'kişinin', level: 'B2' },
    { word: 'opened', meaning: 'açtı', level: 'A1' },
    { word: 'opinions', meaning: 'fikirler', level: 'B1' },
    { word: 'opium-tainted', meaning: 'afyon bulaşmış', level: 'C2' },
    { word: "oughtn't", meaning: 'yapmamalı (ought not)', level: 'B1' },
    { word: 'oval', meaning: 'oval', level: 'B1' },
    { word: 'overclouding', meaning: 'bulutlanma, kararma', level: 'C2' },
    { word: 'pages', meaning: 'sayfalar', level: 'A1' },
    { word: 'paid', meaning: 'ödedi', level: 'A2' },
    { word: 'painted', meaning: 'boyalı, boyanmış', level: 'A2' },
    { word: 'painters', meaning: 'ressamlar', level: 'A2' },
    { word: 'pallid', meaning: 'solgun, benzi atmış', level: 'C2' },
    { word: 'parapet', meaning: 'korkuluk, siper', level: 'C2' },
    { word: 'passed', meaning: 'geçti', level: 'A2' },
    { word: 'patron', meaning: 'hamilik eden kimse', level: 'C1' },
    { word: 'paused', meaning: 'durakladı', level: 'B1' },
    { word: 'paw', meaning: 'pati', level: 'B1' },
    { word: 'peeped', meaning: 'gözetledi', level: 'C1' },
    { word: 'peered', meaning: 'dikkatle baktı', level: 'C1' },
    { word: 'perfume', meaning: 'parfüm', level: 'A2' },
    { word: 'persian', meaning: 'Farsça, İranlı', level: 'B1' },
    { word: 'petticoats', meaning: 'iç etekler', level: 'C1' },
    { word: 'philanthropy', meaning: 'hayırseverlik', level: 'C2' },
    { word: 'philosopher', meaning: 'filozof', level: 'B2' },
    { word: 'pink-flowering', meaning: 'pembe çiçek açan', level: 'C1' },
    { word: 'placed', meaning: 'yerleştirdi', level: 'B1' },
    { word: 'planks', meaning: 'kalaslar', level: 'C1' },
    { word: 'planned', meaning: 'planladı', level: 'A2' },
    { word: 'playing', meaning: 'oynuyor', level: 'A1' },
    { word: 'pleasantly', meaning: 'hoş bir şekilde', level: 'B1' },
    { word: 'plump', meaning: 'tombul', level: 'B2' },
    { word: 'pointed', meaning: 'işaret etti', level: 'B1' },
    { word: 'points', meaning: 'puanlar, noktalar', level: 'A1' },
    { word: 'ponderous', meaning: 'hantal, ağır', level: 'C2' },
    { word: 'possessions', meaning: 'eşyalar, varlıklar', level: 'B2' },
    { word: 'powers', meaning: 'güçler, yetkiler', level: 'B1' },
    { word: "preacher's", meaning: 'vaizin', level: 'C1' },
    { word: 'precautions', meaning: 'önlemler', level: 'B2' },
    { word: 'precious', meaning: 'değerli, kıymetli', level: 'B1' },
    { word: 'prelate', meaning: 'yüksek rütbeli din adamı', level: 'C2' },
    { word: 'presently', meaning: 'şu anda, birazdan', level: 'B2' },
    { word: 'pretended', meaning: 'numara yaptı', level: 'B1' },
    { word: 'printed', meaning: 'basılmış', level: 'B1' },
    { word: 'proceeded', meaning: 'ilerledi, devam etti', level: 'C1' },
    { word: 'producing', meaning: 'üretme', level: 'B1' },
    { word: 'propped', meaning: 'destekledi, dayadı', level: 'C1' },
    { word: 'pulled', meaning: 'çekti', level: 'A2' },
    { word: 'pulsation', meaning: 'nabız atışı', level: 'C2' },
    { word: 'pursued', meaning: 'takip etti, sürdürdü', level: 'C1' },
    { word: 'puzzled', meaning: 'şaşkın, kafası karışık', level: 'B1' },
    { word: 'qualities', meaning: 'nitelikler', level: 'B2' },
    { word: 'quid', meaning: 'sterlin (argo)', level: 'C1' },
    { word: 'ran', meaning: 'koştu', level: 'A1' },
    { word: 'rapt', meaning: 'kendinden geçmiş, dalmış', level: 'C2' },
    { word: 'rasping', meaning: 'tırmalayıcı (ses)', level: 'C2' },
    { word: 'razor', meaning: 'ustura, tıraş bıçağı', level: 'B1' },
    { word: 'reached', meaning: 'ulaştı, uzandı', level: 'A2' },
    { word: 'reactions', meaning: 'tepkiler', level: 'B1' },
    { word: 'realized', meaning: 'fark etti', level: 'B1' },
    { word: 'reasons', meaning: 'sebepler', level: 'A2' },
    { word: 'recalled', meaning: 'hatırladı, anımsadı', level: 'B2' },
    { word: 'reckon', meaning: 'sanmak, hesaplamak', level: 'B1' },
    { word: 'refused', meaning: 'reddetti', level: 'B1' },
    { word: 'rejection', meaning: 'reddetme', level: 'B2' },
    { word: 'reluctance', meaning: 'isteksizlik', level: 'C1' },
    { word: 'remained', meaning: 'kaldı', level: 'B1' },
    { word: 'remembered', meaning: 'hatırladı', level: 'A2' },
    { word: 'removed', meaning: 'kaldırdı, çıkardı', level: 'B1' },
    { word: 'replaced', meaning: 'yerine koydu, değiştirdi', level: 'B1' },
    { word: 'replied', meaning: 'cevap verdi', level: 'A2' },
    { word: 'reposed', meaning: 'yatmak, dinlenmek', level: 'C2' },
    { word: 'resemblance', meaning: 'benzerlik', level: 'C1' },
    { word: 'resting', meaning: 'dinlenme', level: 'A2' },
    { word: 'resumed', meaning: 'kaldığı yerden devam etti', level: 'C1' },
    { word: 'returned', meaning: 'döndü', level: 'A2' },
    { word: 'returns', meaning: 'döner', level: 'A2' },
    { word: 'revealed', meaning: 'açığa çıkardı', level: 'B1' },
    { word: 'revelation', meaning: 'vahiy, ifşa', level: 'C1' },
    { word: 'revolutionized', meaning: 'devrim yarattı', level: 'C1' },
    { word: 'ringing', meaning: 'çınlama, çalma', level: 'B1' },
    { word: 'roar', meaning: 'kükreme', level: 'B1' },
    { word: 'roars', meaning: 'kükrer', level: 'B1' },
    { word: 'ropes', meaning: 'halatlar', level: 'B1' },
    { word: 'rose-leaves', meaning: 'gül yaprakları', level: 'B2' },
    { word: 'roses', meaning: 'güller', level: 'A1' },
    { word: 'rugged', meaning: 'sağlam, engebeli', level: 'C1' },
    { word: 'runs', meaning: 'koşar', level: 'A1' }
];
